# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hobby',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
